springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
server:
  port: 9081


  #datasource
spring:
  application:
    name: demo-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
        namespace: 6d7ab29c-7da9-488c-a319-0f4219de7b1c
        group: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.database.slave}?useSSL=false
    username: ${mysql.user}
    password: ${mysql.password}
    initSize: 5
    maxActive: 20
    minIdle: 5
    maxWait: 5000
    testOnReturn: true
    type: com.alibaba.druid.pool.DruidDataSource

seata:
  # 这里要特别注意和nacos中的配置 service.vgroupMapping.demo_tx_group名对应，值无所谓，service.vgroupMapping是统一的前缀
  tx-service-group: demo_tx_group
  registry:
    type: nacos
    nacos:
      # 配置所在命名空间ID，如未配置默认public空间
      server-addr: ${NACOS_SERVER}
      namespace: 6d7ab29c-7da9-488c-a319-0f4219de7b1c
      group: dev
#      seata的服务名称
      application: seata-server
#      nacos平台的登录账号密码
      userName: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: ${NACOS_SERVER}
      namespace: 6d7ab29c-7da9-488c-a319-0f4219de7b1c
      group: dev
      userName: nacos
      password: nacos
