springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
server:
  port: 9081


  #datasource
spring:
  application:
    name: demo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 1.12.219.137:31048
        namespace: 6d7ab29c-7da9-488c-a319-0f4219de7b1c
        group: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
